create table `exchange` (
    `exchange_seq` bigint not null auto_increment comment '교환내역 seq',
    `barcode_num` varchar(30) not null  comment '쿠폰번호',
    `ver` varchar(10) default null comment 'v10',
    `exchange_type` char(1) default null comment '1:교환, 3:교환취소',
    `coupon_status` char(1) default null comment '0:교환대기(주문 취소가 가능한 상태), 1:교환(주문 취소가 불가능한 상태)',
    `use_balance` int default null comment '사용금액(교환 및 교환 취소 금액)',
    `order_balance` int default null comment '잔액 (해당 교환건 처리 후 남은 잔액) ',
    `product_type` varchar(10) default null comment 'BARCODE:기본상품, AMOUNT:잔액관리권',
    `branch_code` varchar(30) default null comment '지점코드',
    `branch_name` varchar(100) default null comment '지점명',
    `exchange_num` varchar(20) default null comment '교환번호',
    `exchange_date` timestamp default null  comment '교환일',
    `tr_id` varchar(50) not null comment 'PUSH_ID 내역 전달 id',
    `date_time` timestamp default null  comment '전송일시',
    `errmessage` varchar(100) default null comment '에러메시지',
    `res_code` varchar(4) default null comment '성공 : 0000, 실패 : 9999',
    `create_time` timestamp default now()  comment '생성일시',
  primary key (`exchange_seq`),
  key `ix_barcode_num` (`barcode_num`),
  key `ix_exchange_num` (`exchange_num`),
  key `ix_tr_id` (`tr_id`),
  key `ix_exchange_date` (`exchange_date` desc),
  key `ix_date_time` (`date_time` desc)
) engine=innodb auto_increment=101 default charset=utf8mb4 collate=utf8mb4_general_ci comment='쿠폰 교환내역';
