create table `goods` (
    `goods_seq` bigint not null auto_increment comment '상품 seq',
    `goods_id` char(10) not null comment '상품 id(즐거운 생성)',
    `event_seq` int not null comment '이벤트 seq',
    `goods_name` varchar(50) not null comment '상품명',
    `brand_name` varchar(50) not null comment '브랜드명',
    `brand_id` varchar(50) not null comment '브랜드id',
    `product_price` int default null comment '액면가',
    `calculate_price` int default null comment '정산가',
    `expire_date` varchar(15) default null comment '상품 유효기간 : 주문일로부터 (주문당일 1일 기준) 1 : 일까지 Ex ) 0|180 1|2017-08-31',
    `goods_ord` int default null comment '노출순서',
    `goods_color` varchar(15) default null comment '상품 컬러',
    `default_yn` char(1) default 'n' comment '디폴트 상품 여부(Y:디폴트, N:디폴트 아님)',
    `delete_yn` char(1) default 'n' comment '삭제 여부(y:디폴트, n:디폴트 아님)',
    `bacode_yn` char(1) default 'n' comment '바코드 생성유무(y:생성, n:미생성)',
    `statusUpdate_yn` char(1) default 'Y' comment 'Y:쿠폰사용여부 알림, N:쿠폰사용여부 모름',
    `file_img_nm` varchar(128) default null comment '원본파일명',
    `file_img_path` varchar(150) default null comment '파일상대경로',
    `file_img_key` char(150) collate utf8mb4_bin default null comment 'uuid 파일키',
    `create_time` timestamp default now() comment '생성일자',
    `create_user` varchar(64) collate utf8mb4_bin default null comment '생성자',
    `update_time` timestamp default null comment '수정일자',
    `update_user` varchar(64) collate utf8mb4_bin default null comment '수정자',
  primary key (`goods_seq`),
  foreign key (`event_seq`) references `event` (`event_seq`),
  key `ix_goods_id` (`goods_id`),
  key `ix_update_user` (`update_user`),
  key `ix_update_time` (`update_time` desc)
) engine=innodb auto_increment=1001 default charset=utf8mb4 collate=utf8mb4_general_ci comment='상품 관리';
