app:
  scheduler:
    cron:
      clean-logfolder: 0 30 3 * * *
      delete-logfolder: 30
      issue-coupon: 30 0 0 * * *
  logging:
    path: /home/zlgoon/service/stardream/stardream-web/logs
    level: INFO
    compress: gz
  crypto:
    private: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBANONuSALISqs9ImsdvZ2FlaA9Dn4xwPl4B4cDZkr5s29mQHrsTLlE51IVA6+3SBMaqRsGHKux00bLqkwx1Bm4mFrjwgDsKUqhO0ouA59zAEJLFZquv4TmyTQic5ua8568mRB3IuoaINEmCzpFcO4NnT+4f5obK2Vb33pWotflayxAgMBAAECgYEAv45eiINLXucI7fh6J6S5iU5u1mdLXV4y11Czh3RXIwiAmVqfMuR2JD6vzkJI28wV7Bfs8zsLP+hTEeQXNdhTNhmZ+P80ZK3qyBBvIFCfvb2xAoRuEMVDyvYHlwos8mBsSwEg7xyaCm635yftt9d4Z19tFTjDMtQKKSRGTzGa3lkCQQDvyDkilv7Uo1iOTDJo+l6e+ZJoILMNikiM6HFrw8rityCL1N99BAbBmLxifutth3n0HnZPjeVPlYgddKIFQjrTAkEA4dy6quS1iV3StenZt+VFI/aplc08ZvbG8f2BV/ygQU+ESzUh1ut9+9tSz9HM+bEd4eiRkkFOgoTXHRS0Bhl/6wJBAJ3Gfqne9zENhnCjfKwMyoQKriZsFcU8D38AV9lUDMTfQMAhwyispJFwocyhvOHmOf3CqZCxSojyWI0hOJcDPFcCQQDMoR6+FdgjTE3LYsNOSPoLSz756af/4TT9qZ+2B7tpcJF7UfgGr/TEakDs6De9QSrBseOxjlmDBreeMVOo8xFhAkATMnmbQsgNkmjB6zvK6WYD3I+a1Yzr++t5Cc/KuyWBfrs1l/fNng9QXI+qzsjUU3UCZ0tgrHpK1krfQL5AzrC4
    public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDTjbkgCyEqrPSJrHb2dhZWgPQ5+McD5eAeHA2ZK+bNvZkB67Ey5ROdSFQOvt0gTGqkbBhyrsdNGy6pMMdQZuJha48IA7ClKoTtKLgOfcwBCSxWarr+E5sk0InObmvOevJkQdyLqGiDRJgs6RXDuDZ0/uH+aGytlW996VqLX5WssQIDAQAB
  test:
    detail-json-filename: /home/zlgoon/service/stardream/stardream-web/work/selectDetail.json

site:
  network:
    zlgoon: https://tcorp.zlgoon.com
  kb:
    crypto:
      seedKey: 7A306465426230315433586C4E5A566258683448585A4244756833216C217649

spring:
  application:
    name: kbcp
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.1.86:3306/kbcp?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: kbcp
    password: 2024Kbcp!@
    hikari:
      #풀에 유지할 최소 커넥션 갯수
      minimum-idle: 2
      #유휴 상태와 사용중인 커넥션을 포함해서 풀이 허용하는 최대 커넥션 갯수
      maximum-pool-size: 20
      #커넥션이 풀에서 유휴상태로 남을 수 있는 최대 시간을 밀리초단위로 지정
      idle-timeout: 30000
      #풀에서 커넥션을 구할 때 대기시간을 밀리초 단위로 지정합니다. 대기 시간 안에 구하지 못하면 익셉션 발생.
      connection-timeout: 10000
      #커넥션의 최대 유지시간. 이 시간이 지난 커넥션중에서 사용중인 커넥션은 종료된 이후에 풀에서 제거
      max-lifetime: 58000
      validation-timeout: 3000
      hikari.connection-test-query: SELECT 1
  web:
    resources:
      chain:
        strategy:
          content:
            paths: /kb/js/**, /kb/css/**
            enabled: true

mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/config.xml

server:
  port: 10013
