app:
  scheduler:
    cron:
      clean-logfolder: 0 19 10 * * *
      delete-logfolder: 30
      issue-coupon: 0 1 0 * * *
  logging:
    path: /home/zlgoon/service/stardream/stardream-web/logs
    level: DEBUG
    compress: gz
  crypto:
    private: MIICdgIBADAsdvsdbetnNBgkqhkiG9w0BAQEFAaeabb
    public: MIGfMA0GCSqwetrnrfgnsfgnGSIb3DQEBAQUAA4GNAD
  test:
    detail-json-filename: /home/zlgoon/service/stardream/stardream-web/work/selectDetail.json

site:
  network:
    zlgoon: https://test.coupon.com
  kb:
    crypto:
      seedKey: 7A306465426230315433586C4E5A566258683448585A4244756833216C217649 #개발
      #seedKey: 6A552156447545423737344E47357635544B62506D5167463242705948507372 #리얼


spring:
  application:
    name: kbcp
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
    check-template-location: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.16.1.86:3306/kbcp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: kbcp
    #    password: 2024Kbcp!@
    url: jdbc:mysql://localhost:3306/kbcp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dbnlakhbdf
    hikari:
      #풀에 유지할 최소 커넥션 갯수
      minimum-idle: 5
      #유휴 상태와 사용중인 커넥션을 포함해서 풀이 허용하는 최대 커넥션 갯수
      maximum-pool-size: 30
      #커넥션이 풀에서 유휴상태로 남을 수 있는 최대 시간을 밀리초단위로 지정
      idle-timeout: 30000
      #풀에서 커넥션을 구할 때 대기시간을 밀리초 단위로 지정합니다. 대기 시간 안에 구하지 못하면 익셉션 발생.
      connection-timeout: 10000
      #커넥션의 최대 유지시간. 이 시간이 지난 커넥션중에서 사용중인 커넥션은 종료된 이후에 풀에서 제거
      max-lifetime: 58000
      validation-timeout: 3000
      hikari.connection-test-query: SELECT 1
  web:
    resources:
      chain:
        strategy:
          content:
            paths: /kb/js/**, /kb/css/**
            enabled: true

mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/config.xml

server:
  port: 8090